@startuml Token Swap

' The Callee contract performs the swap method
Callee -> ConvexusPool : **swap** ( \n\
  recipient, \n\
  true, \n\
  amount0, \n\
  sqrtPriceLimitX96, \n\
  bytes(recipient) \n\
)

note over ConvexusPool : \
**ConvexusPool** compute \n\
the correct amount1 of token1 \n\
and transfer it to recipient


group Transfer amount1 of token1
  ' The swapped tokens are paid back to the recipient
  ConvexusPool -> Token1 : **transfer** ( \n\
    recipient, \n\
    amount1, { \n\
      "method": "pay" \n\
    } \n\
  )

  Token1 -> recipient : **tokenFallback** ( \n\
    ConvexusPool, \n\
    amount1, { \n\
      "method": "pay" \n\
    } \n\
  )
end group

ConvexusPool -> Callee : **convexusSwapCallback** ( \n\
  amount0, \n\
  amount1, \n\
  recipient \n\
)

note over Callee : \
**Callee** must pay back \n\
the given amount0 and \n\
amount1 or the transaction \n\
will revert

group Transfer amount0 of token0

  ' The Callee contract send the required amount0 of token0
  Callee -> Token0 : **transfer** ( \n\
    ConvexusPool, \n\
    amount0, { \n\
      "method": "pay" \n\
    } \n\
  )

  Token0 -> ConvexusPool : **tokenFallback** ( \n\
    Callee, \n\
    amount0, { \n\
      "method": "pay" \n\
    } \n\
  )

end group

@enduml